 Volume in drive C has no label.
 Volume Serial Number is AE41-5139

 Directory of C:\Projects\automotive-academy-2017-12

12/05/2017  12:08 PM    <DIR>          .
12/05/2017  12:08 PM    <DIR>          ..
12/04/2017  12:04 PM               302 .gitignore
12/05/2017  11:56 AM    <DIR>          app
12/05/2017  11:55 AM               791 integrate.bat
12/05/2017  11:55 AM               388 makefile
12/04/2017  12:04 PM                62 README.md
12/05/2017  11:55 AM    <DIR>          test
               4 File(s)          1,543 bytes
               4 Dir(s)  231,535,759,360 bytes free
